<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-12-22 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 3.2.4 on 2021-10-29 02:06

from django.db import migrations, models
>>>>>>> origin/master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> origin/master
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('word_text', models.CharField(max_length=140)),
                ('date_time', models.DateTimeField(verbose_name='投稿日')),
>>>>>>> origin/master
            ],
        ),
    ]
